#!/usr/bin/env bash
#print bad luck if i % 4 == 0
i=1
while [ $i -lt 11 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
