#!/usr/bin/env bash
#print country names
i=1
while [ $i -lt 21 ]
do
	echo $i
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	((i++))
done
