#!/usr/bin/env bash
# checks if school file is exist

var=school
if [ -a $var ]
then
	echo "school file exists"
	if [ -s $var ]
	then
		echo "school file is not empty"
	else
	then
		echo "school file is empty"
	fi

	if [ -f $var ]
	then
		echo "school is a regular file"
	fi
else
then
	echo "school file does not exist"
fi
