#!/usr/bin/env bash
# checks if school file is exist

var="school"
if [ -f "$var" ]
then
	echo "school file exist"
	if [ -s "$var" ]
	then
		echo "school file is empty"
	else
	then
		echo "school file is not empty"
	fi

	if [ -f "$var" ]
	then
		echo "school is regular file"
	fi
else
then
	echo "school file does not exist"
fi
